name: Manual Practice

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "dev"

jobs:
  practice:
    runs-on: ubuntu-latest

    steps:
      - name: Start
        run: echo "Manual pipeline started"

      - name: Show environment
        run: echo "Environment is ${{ inputs.environment }}"
