name: Manual Practice

on:
  workflow_dispatch:

jobs:
  practice:
    runs-on: ubuntu-latest

    steps:
      - name: Start
        run: echo "Manual pipeline started"

      - name: Show message
        run: echo "CI/CD practice is running"
